### PR TITLE
use switch() instead of multi-if()

### PR DESCRIPTION
**Pull request by niXman**

### CODE REVIEW

**Comment by niXman** [comment]
Hmm...

The `message_too_long`[1] and the `message_size`[2] has the same values. I doubt that it must be so...

[1] https://github.com/niXman/udt/blob/develop/src/udt/common/error/error.h#L21
[2] https://github.com/niXman/udt/blob/develop/src/udt/common/error/error.h#L36

**Comment by securesocketfunneling** [comment]
Thank you for your contribution niXman. We really appreciate that.

We agree with you concerning the error code duplication. Some cleaning must be done here since some codes are not used at all (at first, UDT was fully integrated in SSF). There is old stuff to remove. 

Moreover, we plan to make UDT library headers only as asio is.

Thanks again

**Comment by niXman** [comment]
Okay, and what should I change in this commit?: https://github.com/niXman/udt/commit/9af02a83a68d8a25c37cb1bf679d7d0f3197f1df

**Comment by securesocketfunneling** [comment]
Well, ideally, we need to reference every error codes which are not used in this project and remove them in error.h and error.cpp.
And it seems that the duplicate you reported are not used so you can remove them if you don't mind.

**Comment by niXman** [comment]
Ok, I will do it.

**Comment by niXman** [comment]
And what about this commit?: https://github.com/niXman/udt/commit/6fa25c00851b08e3cca7cea788f6075371e638f8

**Comment by securesocketfunneling** [comment]
Good point with the typo. Maybe static_cast could be used here

**Comment by niXman** [comment]
I don't think that in this case it makes a difference.

**Comment by securesocketfunneling** [comment]
This will not make a difference indeed but it is more explicit and readable.

Anyway, this change must be done on the whole project. We will do that later.

**Pull request merged**
